from pathlib import Path
from curator.models import StructuredFact, META_TYPE_PREFIX
from curator.backend.interface import MemoryBackend


class SyncEngine:
    """Двусторонняя синхронизация: .md ↔ memory backend."""

    INDEX_NAME = "index.md"
    # Автогенерируемый index создаю/обновляю ТОЛЬКО с этим маркером.
    # index.md без маркера — ручной файл пользователя (save-knowledge и
    # прочие): его не трогаем, навигацию ему не навязываем.
    INDEX_MARKER = "<!-- curator: autogenerated index -->"

    def __init__(self, backend: MemoryBackend, base_dir: Path):
        self.backend = backend
        self.base_dir = base_dir
        # (glob, mode) таргетов карты — лениво, один раз на инстанс
        self._modes_cache: list[tuple[str, str]] | None = None

    def _map_path(self) -> Path | None:
        import os
        env = os.getenv("CURATOR_MAP", "").strip()
        if env:
            return Path(env).expanduser()
        candidate = self.base_dir / "DOCUMENTATION-MAP.md"
        return candidate if candidate.exists() else None

    def _mode_for(self, source_file: str) -> str:
        """mode таргета карты для пути (update/append/readonly); нет карты
        или матча — update (текущее поведение)."""
        if self._modes_cache is None:
            map_path = self._map_path()
            if map_path is None:
                self._modes_cache = []
            else:
                from curator.routing.map_router import target_modes
                self._modes_cache = target_modes(map_path)
        import fnmatch
        for pattern, mode in self._modes_cache:
            if fnmatch.fnmatch(source_file, pattern):
                return mode
        return "update"

    def write_fact_to_md(self, fact: StructuredFact) -> Path:
        if not fact.source_file:
            raise ValueError("Fact has no source_file")
        mode = self._mode_for(fact.source_file)
        if mode == "readonly":
            # Карта запрещает запись в этот таргет («использовать только как
            # контекст») — честный отказ, capture покажет ⚠
            raise ValueError(f"таргет readonly: {fact.source_file} — запись в .md запрещена картой")
        md_path = self._resolve_md_path(fact.source_file)
        md_path.parent.mkdir(parents=True, exist_ok=True)

        if not md_path.exists():
            md_path.write_text(self._render_fact(fact), encoding="utf-8")
        else:
            self._upsert_fact_in_md(md_path, fact, mode)

        self._rebuild_index()
        return md_path

    def update_fact_in_md(self, fact: StructuredFact) -> Path:
        if not fact.source_file:
            raise ValueError("Fact has no source_file")
        md_path = self._resolve_md_path(fact.source_file)
        self._upsert_fact_in_md(md_path, fact)
        return md_path

    def remove_fact_from_md(self, fact: StructuredFact) -> Path | None:
        if not fact.source_file:
            return None
        md_path = self._resolve_md_path(fact.source_file)
        if not md_path.exists():
            return None

        content = md_path.read_text(encoding="utf-8")
        lines = content.split("\n")
        idx = self._find_fact_section(lines, fact.title)
        if idx is None:
            return None

        lines[idx:self._content_end(lines, idx)] = [
            f"### {fact.title} [УСТАРЕЛО]",
            "",
            "*Это знание помечено как устаревшее.*",
        ]
        self._write_lines(md_path, lines)
        return md_path

    def rewrite_status(self, fact: StructuredFact) -> Path | None:
        """Отразить смену статуса факта в .md — человеко-читаемый слой
        не должен врать о жизненном цикле.

        deprecated → маркер [УСТАРЕЛО] (ingest такие секции не воскрешает);
        остальные статусы (hypothesis) → перерендер секции. Факт без
        source_file (decay по usage, легаси) — молча пропускается.
        """
        if not fact.source_file:
            return None
        if fact.status == "deprecated":
            path = self.remove_fact_from_md(fact)
            if path is not None:
                self._rebuild_index()
            return path
        return self.write_fact_to_md(fact)

    def _render_fact(self, fact: StructuredFact) -> str:
        status_labels = {"verified": "Подтверждено", "hypothesis": "Гипотеза", "deprecated": "Устарело"}
        tags = ", ".join(fact.tags)
        return (
            f"### {fact.title}\n\n"
            f"{fact.content_summary}\n\n"
            f"*Тип:* {fact.type} | *Статус:* {status_labels.get(fact.status, fact.status)} | *Теги:* {tags}\n"
            f"*Файл:* {fact.source_file}\n"
        )

    def _upsert_fact_in_md(self, md_path: Path, fact: StructuredFact, mode: str = "update") -> None:
        content = md_path.read_text(encoding="utf-8")
        lines = content.split("\n")
        idx = self._find_fact_section(lines, fact.title)

        if idx is not None:
            if mode == "append":
                # append: «добавлять запись, сохраняя историю» — существующую
                # секцию не перезаписываем
                return
            rendered = self._render_fact(fact).rstrip("\n").split("\n")
            lines[idx:self._content_end(lines, idx)] = rendered
            self._write_lines(md_path, lines)
        else:
            md_path.write_text(content + f"\n\n---\n\n{self._render_fact(fact)}", encoding="utf-8")

    def _write_lines(self, md_path: Path, lines: list[str]) -> None:
        """Единая точка записи .md: гарантирует финальный перевод строки
        (POSIX), чтобы инвариант не зависел от формы слайса."""
        text = "\n".join(lines)
        if text and not text.endswith("\n"):
            text += "\n"
        md_path.write_text(text, encoding="utf-8")

    def _resolve_md_path(self, source_file: str) -> Path:
        """Путь .md строго внутри base_dir — source_file не может выйти за
        sandbox и не может содержать перевод строки (сломал бы формат .md)."""
        if "\n" in source_file or "\r" in source_file:
            raise ValueError(f"source_file содержит перевод строки: {source_file!r}")
        md_path = (self.base_dir / source_file).resolve()
        if not md_path.is_relative_to(self.base_dir.resolve()):
            raise ValueError(f"source_file вне base_dir: {source_file}")
        return md_path

    def _find_fact_section(self, lines: list[str], title: str) -> int | None:
        """Индекс строки-заголовка нашей секции факта или None.

        Совпадение строго по целой строке `### {title}` (не подстрокой) и только
        для секций в нашем формате рендера (`*Тип:*`): чужая одноимённая секция
        пользователя не считается нашей и не затирается.
        """
        marker = f"### {title}".strip()
        for i, line in enumerate(lines):
            if line.strip() != marker:
                continue
            for j in range(i + 1, self._section_end(lines, i)):
                if lines[j].startswith(META_TYPE_PREFIX):
                    return i
        return None

    def _section_end(self, lines: list[str], idx: int) -> int:
        """Конец секции: первая строка-заголовок ЛЮБОГО уровня (`#`, `##`,
        `###`...) после idx — или конец файла. Заголовок чужой ## главы не
        принадлежит нашей секции и не может быть съеден."""
        for j in range(idx + 1, len(lines)):
            if lines[j].startswith("#"):
                return j
        return len(lines)

    def _content_end(self, lines: list[str], idx: int) -> int:
        """Конец ЗАМЕНЯЕМОГО диапазона: как _section_end, но не захватывает
        хвостовые пустые строки и `---`-разделители перед следующей секцией —
        они сохраняются на месте."""
        end = self._section_end(lines, idx)
        while end > idx + 1 and lines[end - 1].strip() in ("", "---"):
            end -= 1
        return end

    def _rebuild_index(self) -> None:
        """Навигация не протухает: после каждой записи пересобрать
        index.md — живые факты по файлам.

        Охрана согласия: index.md без INDEX_MARKER — ручной файл
        пользователя, не трогаем. Формат index.md — только `##`-заголовки
        и буллеты: `###`-секций нет, ingest не примет его за факты.
        """
        index_path = self.base_dir / self.INDEX_NAME
        if index_path.exists():
            try:
                head = index_path.read_text(encoding="utf-8")[:512]
            except OSError:
                return
            if self.INDEX_MARKER not in head:
                return

        if not self.base_dir.exists():
            return

        lines = [self.INDEX_MARKER, "", "# База знаний", ""]
        md_files = sorted(
            p for p in self.base_dir.rglob("*.md")
            if p.name != self.INDEX_NAME and p.is_file()
        )
        for md_file in md_files:
            try:
                titles = self._read_fact_titles(md_file)
            except OSError:
                continue
            if not titles:
                continue
            rel = md_file.relative_to(self.base_dir).as_posix()
            lines.append(f"## {rel}")
            for title in titles:
                lines.append(f"- [{title}]({rel})")
            lines.append("")

        self._write_lines(index_path, lines)

    def _read_fact_titles(self, md_path: Path) -> list[str]:
        """Живые факты нашего формата в файле: заголовки `### {title}` с
        мета-строкой рендера, без маркера [УСТАРЕЛО]."""
        lines = md_path.read_text(encoding="utf-8").split("\n")
        titles = []
        i = 0
        while i < len(lines):
            if lines[i].startswith("### "):
                end = self._section_end(lines, i)
                is_ours = any(
                    lines[j].startswith(META_TYPE_PREFIX)
                    for j in range(i + 1, end)
                )
                if is_ours and not lines[i].rstrip().endswith("[УСТАРЕЛО]"):
                    titles.append(lines[i].removeprefix("### ").strip())
                i = end
            else:
                i += 1
        return titles